USE COMPANY;
GO
/*
CREATE PROCEDURE PROC_EMPDETAILS;  -- stored procedure with No parameter

AS
BEGIN 
      SELECT *FROM Employee;

END
GO

EXECUTE PROC_EMPDETAILS;
GO
use sample;
GO
*/

/* STORED PROCEDURE WITH PARAMETER --(LOCATION)*/
/*
CREATE PROCEDURE PROC_DETAILS_OF_EMLPOYEE (@Location AS VARCHAR(100))
AS
BEGIN
      SELECT *FROM Employee  AS E INNER JOIN Deparment_INFO AS D ON 
	  E.P_ID=D.D_id 
	  WHERE D.D_location=@Location

END
GO
EXECUTE PROC_DETAILS_OF_EMLPOYEE @Location='PUNE'
GO

EXECUTE PROC_DETAILS_OF_EMLPOYEE @Location='CHALISGAON'
GO */


--ALTERING THE STORED PROCEDURE
/*
ALTER PROCEDURE PROC_EMPDETAILS--ALSO MODIFY  BY USING MODIFY WHICH PRESENT IN STORED PRODECURE
AS
BEGIN
      SELECT  EmpName,Salary,D_Name,D_Location from Employee E INNER JOIN Deparment D
	  ON E.P_ID=D.D_ID    
END

EXECUTE  PROC_EMPDETAILS*/


SELECT *FROM sys.sql_modules;-- To see the stored procedure Name