CREATE DATABASE USER_LOGIN;
use USER_LOGIN;

CREATE TABLE TABLE_USER_LOGIN
( USER_ID INT PRIMARY KEY IDENTITY,
  USER_NAME VARCHAR(50) NOT NULL UNIQUE,
  EMAIL_ID VARCHAR(50)NOT NULL UNIQUE,
  PASSWORD VARCHAR(50) NOT NULL
 );

 INSERT INTO TABLE_USER_LOGIN VALUES
 ('Mihir','Mihirvansh@.com','mihir@123' );

 INSERT INTO TABLE_USER_LOGIN VALUES
 ('Harshal','harshalD@.com','Harshal@123' );

 INSERT INTO TABLE_USER_LOGIN VALUES
 ('Nishant','NishantD@.com','Nishant@321' );

 ALTER TABLE TABLE_USER_LOGIN 
 ADD CITY VARCHAR(50) ;

 UPDATE TABLE_USER_LOGIN SET CITY='JALAGON' WHERE USER_ID=1;
 UPDATE TABLE_USER_LOGIN SET CITY='JALAGON' WHERE USER_ID=2;
 UPDATE TABLE_USER_LOGIN SET CITY='CHALISGAON' WHERE USER_ID=3;

 SELECT *from Table_USER_LOGIN;

  /*BOOLEAN OPERATOR*/

 select USER_NAME from TABLE_USER_LOGIN WHERE EMAIL_Id='MihirVansh@.com' AND PASSWORD='mihir@123';

 select USER_NAME from TABLE_USER_LOGIN WHERE EMAIL_Id='MihirVansh@.com' OR PASSWORD='mihir@123';

 select *from TABLE_USER_LOGIN WHERE  USER_Name='Nishant';
 select *from TABLE_USER_LOGIN WHERE   NOT USER_Name='Nishant';
 select *from TABLE_USER_LOGIN WHERE  USER_Name !='Nishant';

 select *from TABLE_USER_LOGIN WHERE USER_Id BETWEEN 1 AND 3;
 SELECT *FROM TABLE_USER_LOGIN WHERE  USER_NAME LIKE'm%';

 /*DATE AND TIME FUNCTION*/
 
 SELECT GETDATE();
 SELECT SYSDATETIME();
 SELECT CURRENT_TIMESTAMP;
 SELECT DATENAME(MONTH, CURRENT_TIMESTAMP);
 SELECT DATENAME(YEAR ,CURRENT_TIMESTAMP);
 SELECT DATENAME(DAYOFYEAR, CURRENT_TIMESTAMP);
 SELECT DATENAME(HOUR ,CURRENT_TIMESTAMP);
 SELECT DATEDIFF(YEAR, 'DECEMBER 20 2001',CURRENT_TIMESTAMP) AS AGEINYEAR;
 SELECT DATEADD(YEAR,100, CURRENT_TIMESTAMP) AS YEAR;


 /*GRUOP BY FUNCTION*/
 SELECT CITY FROM TABLE_USER_LOGIN GROUP BY CITY;

/*TO COPY DATABASE FROM ONE TO ANOTHER*/
 SELECT * INTO OK FROM EmployeeDB.DBO.Employee_info;
 SELECT *FROM OK;





