/*SELECT GETDATE() AS 'PREVIOUS TIME';
GO
BEGIN
    WAITFOR TIME '12:43:00' ;--USED TO SET TIME
	SELECT * from Sample.dbo.Employee;
	SELECT GETDATE()AS 'CURRENT TIME';

END
GO
BEGIN 
SELECT GETDATE()AS 'CURRENT TIME';
END

GO
*/

SELECT GETDATE() AS 'PREVIOUS TIME';
GO
BEGIN
    WAITFOR DELAY '00:00:10' ;--USED TO ADD TIME 
	SELECT * from Sample.dbo.Employee SELECT * FROM SAMPLE .DBO.Deparment_INFO;
	SELECT GETDATE()AS 'CURRENT TIME';

END
GO
BEGIN 
SELECT GETDATE()AS 'CURRENT TIME';
END