
/* USE OF BATCHES FIRST IS DATABASE NAME ,SECOND AND THIRED ARE DECLARE 
USING SAME NAME (WE CAN USE SAME NAME FOR DIFFERENT BATCHES (THIS IS THE BENIFIT) 
OF BATCH */
--GO COMMAND IS NECESSARY TO USE  
 Use Sample;
GO

DECLARE @NAME VARCHAR(50);
SELECT @NAME='Swapnil';
SELECT @Name AS 'Name';
GO

DECLARE @NAME VARCHAR(50);
SELECT @NAME='Mahajan';
SELECT @Name AS 'Last_Name';
GO
